### ISSUE TITLE
syntax error, unexpected '|'

### ISSUE THREAD

**Issue by TechOverflow** [sauladam/shipment-tracker#13]
I updated to v0.5. Now using 

```
$packageInput = '12345';
$fedexTracker = ShipmentTracker::get('Fedex');
$result = $fedexTracker->track($packageInput, 'en');
```

I get

```
<b>Parse error</b>:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in <b>/vendor/nesbot/carbon/src/Carbon/Traits/Date.php</b> on line <b>1024</b><br />
```

Any idea how I could be causing this error? I simply want to get all results for that number.

**Comment by TechOverflow** [comment]
```
"require": {
    ...
    "nesbot/carbon": ">=1.20"
  },
```
needs to be
```
"require": {
    ...
    "nesbot/carbon": ">=1.20  <=2.0"
  },
```
otherwise Carbon gets updated by composer to version 2.latest

**Comment by sauladam** [comment]
Hey @TechOverflow,

thank you for your feedback. The error you mentioned sounds pretty much like something PHP 5.x would say when running PHP 7.x code. So I'm guessing you're running PHP 5.x while Carbon >2.0 and some other dependencies require PHP ^7.1.

I'm not sure if limiting the Carbon version here is the right approach though since this package runs perfectly fine on PHP 7.x. So I suggest you just pull in Carbon <2 in your own project.

Just add `"nesbot/carbon": "^1.36.2"` as a dependency to your own composer.json and you should be good to go. This package will then use that version.
