### ISSUE TITLE
[DHL] Same Result on multiple trackings

### ISSUE THREAD

**Issue by hahrens** [sauladam/shipment-tracker#9]
Hi there,

i just wanted to track multiple Shiments from DHL as i figured out that i only get the real result for the first one.

Here's my (simplified) Code: 
```php
$trackingId = 'INSERT_TRACKING_ID_HERE';
$tracker = \Sauladam\ShipmentTracker\ShipmentTracker::get('DHL');
$trackingResult = $tracker->track($trackingId, 'de');
// $trackingResult is the correct one

$anotherTrackingId = 'INSERT_ANOTHER_TRACKING_ID_HERE';
$anotherTrackingResult = $tracker->track($anotherTrackingId, 'de');
// $anotherTrackingResult is the same as above in $trackingResult
```

So after i've been a bit confused and searching for an error in my code i dig into your's and figured out, that you cache parsedJson and return it in https://github.com/sauladam/shipment-tracker/blob/master/src/Trackers/DHL.php#L124 before it would re-parsed.

I don't know why this is required/used, but it now requires to create a whole new Tracker-Instance every time a new Tracking is needed. I fixed this for me by quick+dirty adding `$this->parsedJson = null;` to the [getTrack](https://github.com/sauladam/shipment-tracker/blob/master/src/Trackers/DHL.php#L58)-Method. It looks now:

```php
    // ...
    protected function getTrack(DOMXPath $xpath)
    {
        $track = new Track;
        
        // Reset cached JSON
        $this->parsedJson = null;

        foreach ($this->getEvents($xpath) as $event) {
           // ...
```

Could you please check if the JSON-Cache is needed and/or reset it?

**Comment by sauladam** [comment]
Excellent catch, thank you very much!

The result is cached in case we have to figure out the recipient after recording all events. With the cached JSON we don't need to dive into the DOM in order to parse the relevent part out again. It sure would not make much differece performance wise, but it just bugs me :-D

The ```getTrack``` method might be a good place to clear the cache but I decided to put the logic inside the ```track``` method by overriding it, becaus this is part of the actual public interface and it's what actually gets called when a new tracking request starts so both actions are somehow related.

Thanks again and make sure to update to 0.4.13
